name: "Manage Awaiting Response Label"

on:
  issue_comment:
    types: [created]

permissions: {} # deny default GITHUB_TOKEN permissions (workflow uses custom OSS_PROJECT_GH_TOKEN)

jobs:
  run:
    uses: "anchore/workflows/.github/workflows/remove-awaiting-response-label.yaml@main"
    secrets:
      token: ${{ secrets.OSS_PROJECT_GH_TOKEN }}
